# Generated by Django 5.2.3 on 2025-06-16 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '待初审'), ('in_review', '专家审核中'), ('revision_needed', '待修改'), ('approved', '审核通过'), ('rejected', '审核未通过')], default='draft', max_length=20, verbose_name='项目状态')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('proposal', '项目申报书'), ('consent', '知情同意书'), ('waiver', '豁免知情同意申请'), ('other', '其他材料')], max_length=20, verbose_name='文件类型')),
                ('file', models.FileField(upload_to='project_files/%Y/%m/%d/', verbose_name='上传的文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.project', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('approve', '同意'), ('revise', '修改后同意'), ('reject', '不同意')], max_length=20, verbose_name='审查结论')),
                ('comments', models.TextField(verbose_name='具体审查意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审查时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.project', verbose_name='审查项目')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_assigned', to=settings.AUTH_USER_MODEL, verbose_name='审查专家')),
            ],
        ),
    ]
