# Generated by Django 5.2.3 on 2025-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '待初审'), ('in_review', '专家审核中'), ('awaiting_decision', '待管理员决策'), ('revision_needed', '待修改'), ('approved', '审核通过'), ('rejected', '审核未通过')], default='draft', max_length=20, verbose_name='项目状态'),
        ),
    ]
