# Generated by Django 5.2.3 on 2025-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='管理员最终意见'),
        ),
    ]
